# PyNVR Configuration File

app:
  app_name: PyNVR
  version: 0.1.0
  default_layout: 2x2
  recording_path: recordings
  log_level: INFO
  use_hardware_acceleration: true
  max_reconnect_attempts: 3
  reconnect_delay: 5

cameras:
  # 실제 카메라 설정 예시

  - camera_id: cam_01
    name: Trolley Camera 1
    rtsp_url: rtsp://admin:trolleycam1~@192.168.0.131:554/Streaming/Channels/102
    enabled: true
    username:   # URL에 포함되어 있으므로 비워둠
    password:   # URL에 포함되어 있으므로 비워둠
    use_hardware_decode: false  # 소프트웨어 디코딩 사용
    recording_enabled: false
    motion_detection: false

  # 인증 정보를 분리하는 방법 (대체 방법)
  - camera_id: cam_02
    name: Trolley Camera 2
    rtsp_url: rtsp://admin:trolleycam1~@192.168.0.131:554/Streaming/Channels/102
    enabled: true
    username:   # URL에 포함되어 있으므로 비워둠
    password:   # URL에 포함되어 있으므로 비워둠
    use_hardware_decode: false  # 소프트웨어 디코딩 사용
    recording_enabled: false
    motion_detection: false

  # 추가 카메라 예시
  - camera_id: cam_03
    name: Camera 3
    rtsp_url: rtsp://admin:trolleycam1~@192.168.0.131:554/Streaming/Channels/102
    enabled: true
    username:
    password:
    use_hardware_decode: false  # 소프트웨어 디코딩 사용
    recording_enabled: false
    motion_detection: false

  - camera_id: cam_04
    name: Camera 4
    rtsp_url: rtsp://admin:trolleycam1~@192.168.0.131:554/Streaming/Channels/102
    enabled: true
    username:
    password:
    use_hardware_decode: false  # 소프트웨어 디코딩 사용
    recording_enabled: false
    motion_detection: false